[Task] Create homepage with HTML
st-khanhngo/FE-Internship-2023_Khanh-Ngo-H_FE-Exercise pull request #6
Opened 2023-08-04 09:22 UTC by st-khanhngo

### References
> [Figma design](https://www.figma.com/file/CUQiZbPKOlfjHZn9hBqrPh/Fashion?type=design&node-id=8-194&mode=design&t=QAocD6omAOeXQkSi-0)

### Description
> Create HTML based on design (Home1)

### Checklist
- [x] App run correctly
- [x] The code has been tested in the local environment.

2023-08-05 03:26 UTC, st-quangnguyen2 commented on HTML Exercise/index.html
> +    </section>
`section` không nằm trong `header`

2023-08-05 03:29 UTC, st-quangnguyen2 commented on HTML Exercise/index.html
> +
em đang chia layout bị sai dẫn đên dùng thẻ `section` sai cách.
nguyên phần này là một `section`, mấy cái `item`, `card` thì không phải `section` , tương tự cho những phần dưới
![image](https://github.com/st-khanhngo/FE-Internship-2023_Khanh-Ngo-H_FE-Exercise/assets/81966530/2075528c-9b42-4636-a02b-5ea6710c712b)

2023-08-05 03:30 UTC, st-quangnguyen2 commented on HTML Exercise/index.html
> +          <span class="price">$119.99</span>
những `item` hay `card` mà có thể click để đến trang khác thì bọc trong thẻ `a`

2023-08-05 03:32 UTC, st-quangnguyen2 commented on HTML Exercise/index.html
> +          <span class="price">$119.99</span>
tên `product` thường dùng thẻ `h4`, không dùng `p` ở đây

2023-08-05 03:35 UTC, st-quangnguyen2 commented on HTML Exercise/index.html
> +      <h2>Products in today</h2>
như anh cmt ở trên thì đây là 1 `section`, và mình sẽ dùng `section` thay cho `div`.
class của một `section` sẽ như thế này `section section-{sectionName}` ở trường hợp này là `section section-product`

2023-08-05 03:38 UTC, st-quangnguyen2 commented on HTML Exercise/index.html
> +      </section>
nếu nhìn vào design em sẽ dễ thấy là đây là một `list` các `icon` có `link`.
Vì là list nên sẽ dùng `ul li` cho phần này

2023-08-05 03:42 UTC, st-quangnguyen2 commented on HTML Exercise/index.html
> +    </section>
tương tự phần icon link thì đây nó cũng là một list.
List trong list
List lớn gồm 3 cái cột, mỗi cột cũng là một `list` chứa các `item` là `footer-nav-link`

2023-08-05 03:48 UTC, st-quangnguyen2 commented on HTML Exercise/index.html
> +    </div>
tất cả những chỗ có UI là các item có hình thái tương tự nhau thì nó sẽ là một `list` và mình sẽ dùng `ul li` trong trường hợp này.
anh sẽ vd dựa trên các class có sẵn em đã đặt, chưa bàn về chuyện nó có hợp lý hay không.
em fix tương tự với các phần còn lại
Vd:
```
ul.note-list > li.note-item > div.note > ...
```

2023-08-05 03:50 UTC, st-quangnguyen2 requested changes
@st-khanhngo check cmts

2023-08-06 17:28 UTC, st-quangnguyen2 commented on HTML Exercise/index.html
> +      </nav>
bổ sung class cho `nav` `ul` `li`

2023-08-06 17:30 UTC, st-quangnguyen2 commented on HTML Exercise/index.html
> +    </ul>
nguyên phần này là một `section` nằm trong `main`

2023-08-06 17:31 UTC, st-quangnguyen2 commented on HTML Exercise/index.html
> +
ở bài tập này em dùng `h1` bọc `logo`

2023-08-06 17:32 UTC, st-quangnguyen2 commented on HTML Exercise/index.html
> +      </a>
vì `h1` đã được dùng cho `logo` em dùng thẻ khác thay thế và thêm class cho nó.
thêm class cho thẻ `a`
`i` chưa đủ class `icon icon-arrow`

2023-08-06 17:33 UTC, st-quangnguyen2 commented on HTML Exercise/index.html
> +          <p class="note-name">Free Shipping</p>
dùng `h4` cho `name/title`

2023-08-06 17:34 UTC, st-quangnguyen2 commented on HTML Exercise/index.html
> +        <p class="highlight-desc">New arrivalsare now in!</p>
ở đây nên là `desc` hay `title`

2023-08-06 17:35 UTC, st-quangnguyen2 commented on HTML Exercise/index.html
> +      </div>
đây là một list em dùng `ul > li > div...`

2023-08-06 17:37 UTC, st-quangnguyen2 commented on HTML Exercise/index.html
> +        <a href=""><button class="highlight-action">MORE DETAILS</button></a>
thêm class cho `a`
`highlight-action` nên được dùng cho một `wrapper` chứa `button`
class của button sẽ là `btn btn-...`

2023-08-06 17:40 UTC, st-quangnguyen2 commented on HTML Exercise/index.html
> +      <a href=""><button class="recommend-action">SHOW MORE</button></a>
`recommend-title` -> `section-title`
thêm class cho `a`
`recommend-action` -> `section-action` và dùng cho wrapper
class của butotn như cmt phía trên `btn btn-...`

2023-08-06 17:40 UTC, st-quangnguyen2 commented on HTML Exercise/index.html
> +            <a href="">
thêm class cho `a`

2023-08-06 17:40 UTC, st-quangnguyen2 commented on HTML Exercise/index.html
> +              <img src="images/image.png" alt="T-Shirt Summer Vibes">
thêm class cho `img`

2023-08-06 17:41 UTC, st-quangnguyen2 commented on HTML Exercise/index.html
> +            <p class="info-title">Free Shipping</p>
dùng `h4` cho `title/name`

2023-08-06 17:42 UTC, st-quangnguyen2 commented on HTML Exercise/index.html
> +    </div>
đây là một `section`, em sửa và đặt class tương ứng cho đúng

2023-08-06 17:42 UTC, st-quangnguyen2 commented on HTML Exercise/index.html
> +      <img src="" alt="">
class cho `img`

2023-08-06 17:45 UTC, st-quangnguyen2 commented on HTML Exercise/index.html
> +      </ul>
thêm class cho `li`
với icon class sẽ có dạng ntn `ic ic-{name}` hoặc `icon icon-{name}`
ở đây mấy cái social icon còn link tới trang khác, nên em bọc `a` và thêm class cho nó

2023-08-06 17:45 UTC, st-quangnguyen2 commented on HTML Exercise/index.html
> +      <li>
thêm class cho `li`

2023-08-06 17:46 UTC, st-khanhngo commented on HTML Exercise/index.html
> +    </ul>
vậy header chỉ là phần này thôi ạ?
<img width="436" alt="Screen Shot 2023-08-07 at 00 45 21" src="https://github.com/st-khanhngo/FE-Internship-2023_Khanh-Ngo-H_FE-Exercise/assets/141203042/5dd5a27d-a5f1-4020-afb2-92a4b9a0795b">

2023-08-06 17:46 UTC, st-quangnguyen2 commented on HTML Exercise/index.html
> +          </li>
cái này đem ra ngoài `ul`

2023-08-06 17:46 UTC, st-quangnguyen2 commented on HTML Exercise/index.html
> +          <li><a href="">Order Status</a></li>
thêm class cho `li` và `a`

2023-08-06 17:47 UTC, st-quangnguyen2 commented on HTML Exercise/index.html
> +    </ul>
yep, với design này thì header chi có thế thôi @st-khanhngo

2023-08-06 17:49 UTC, st-quangnguyen2 commented on HTML Exercise/index.html
> +<!DOCTYPE html>
tên folder đang sai format
`HTML Exercise` -> `html-exercise`

2023-08-07 01:44 UTC, st-quangnguyen2 commented on html-exercise/index.html
> +      <3>Products in today</3>
sai thẻ và thiếu class

2023-08-07 02:12 UTC, st-manhle requested changes

2023-08-07 02:12 UTC, st-manhle commented on html-exercise/index.html
> +    <h1><img class="img img-logo" src="assets/images/Logo.png" alt="Logo"></h1>
Thông thường khi bấm vào logo sẽ navigate sang trang home => thêm thẻ `a`
```<h1> - <a> - <img>```
Attribute `alt` của img phải giống thẻ `title` => Tăng SEO

2023-08-07 02:12 UTC, st-manhle commented on html-exercise/index.html
> +    </nav>
`nav` thì luôn thuộc header nên không cần đặt tên là `header-nav`
E sửa theo cấu trúc sau nghe
```
nav.nav-main
  ul.nav-list
     li.nav-item
        a.nav-link
```

2023-08-07 02:12 UTC, st-manhle commented on html-exercise/index.html
> +    <div class="header-action">
Không cần thẻ div này

2023-08-07 02:12 UTC, st-manhle commented on html-exercise/index.html
> +      <ul class="header-action-list">
E có thể bỏ prefix `header` vì nằm trong thẻ header rồi thì sẽ hiểu là action của header

2023-08-07 02:12 UTC, st-manhle commented on html-exercise/index.html
> +      </a>
Bọc lại bằng thẻ div để dễ dàng di chuyển cả block này khi style

2023-08-07 03:04 UTC, st-manhle approved these changes

2023-08-07 06:55 UTC, st-quangnguyen2 commented on html-exercise/index.html
> +    </h1>
chưa có class cho `h1`, với format code chỗ này lại

2023-08-07 06:56 UTC, st-quangnguyen2 commented on html-exercise/index.html
> +      </div>
`banner` -> `section`

2023-08-07 06:57 UTC, st-quangnguyen2 commented on html-exercise/index.html
> +      </div>
`recommend` -> `section`

2023-08-07 06:57 UTC, st-quangnguyen2 commented on html-exercise/index.html
> +      <h3 class="info-title">Why should you choose us?</h3>
`info` -> `section`

2023-08-07 06:59 UTC, st-quangnguyen2 commented on html-exercise/index.html
> +        <h5 class="footer-nav-title">Shopping online</h5>
mình sẽ thông nhất không dùng `heading` ở `footer`. dùng `p` thay thế

2023-08-07 07:00 UTC, st-quangnguyen2 requested changes
@st-khanhngo check cmts

2023-08-08 04:32 UTC, st-quangnguyen2 approved these changes

2023-08-08 04:32 UTC, merged