[Task] Add CSS to page
st-khanhngo/FE-Internship-2023_Khanh-Ngo-H_FE-Exercise pull request #9
Opened 2023-08-08 10:12 UTC by st-khanhngo

### References
> [Figma design](https://www.figma.com/file/CUQiZbPKOlfjHZn9hBqrPh/Fashion?node-id=8%3A279&mode=dev)

### Description
> Create CSS file to match design (Home1)

### Screenshots
![screencapture-localhost-5500-html-exercise-2023-08-08-17_06_48-min](https://github.com/st-khanhngo/FE-Internship-2023_Khanh-Ngo-H_FE-Exercise/assets/141203042/1d7540d5-5809-4104-a267-c19c3c6be5ee)

### Checklist
- [x] App run correctly
- [x] The code has been tested in the local environment.
- [ ] No convention errors

2023-08-08 13:54 UTC, st-quangnguyen2 commented on html-exercise/assets/css/reset.css
> +}
phần này không nằm trong file `reset`, em có thể đưa nó vào `layout`

2023-08-08 13:54 UTC, st-quangnguyen2 commented on html-exercise/assets/css/reset.css
> +
đưa vào file `icon`

2023-08-08 13:55 UTC, st-quangnguyen2 commented on html-exercise/assets/css/reset.css
> +}
em có thế khai bào biến cho các `color` `font-size` `font-weight` ở file `variables`

2023-08-08 13:56 UTC, st-quangnguyen2 commented on html-exercise/assets/css/style.css
> +}
đưa vào file `header`

2023-08-08 13:56 UTC, st-quangnguyen2 commented on html-exercise/assets/css/style.css
> +
đưa vào file `icon`

2023-08-08 13:57 UTC, st-quangnguyen2 commented on html-exercise/assets/css/style.css
> +}
đưa vào file `section`

2023-08-08 13:57 UTC, st-quangnguyen2 commented on html-exercise/assets/css/style.css
> +section .section-title {
`section .section-title` -> `.section .section-title`

2023-08-08 14:04 UTC, st-quangnguyen2 commented on html-exercise/assets/css/style.css
> +}
anh nghĩ chô này mình bỏ `-note` rồi đưa mấy cái này vào file `icon` để dùng lại đc đấy
khi đó class của icon trong note sẽ thành `icon icon-{name} note-icon`
- `icon`: style cung cho icon
- `icon-{name}`: định danh icon để bỏ source ảnh
- `note-icon`: để css riêng cho `icon` nằm trong `note` nếu cần

2023-08-08 14:04 UTC, st-quangnguyen2 commented on html-exercise/assets/css/style.css
> +}
`.icon-note` -> `.note .note-icon`

2023-08-08 14:08 UTC, st-quangnguyen2 commented on html-exercise/assets/css/style.css
> +
thêm `.note ` vào `selector`
```
.note
.note .note-title
.note .note-content
.note .note-desc
```
mục đích là css của các thành phần `.note` chỉ được apply khi nó nằm bên trong `note`
tương tự với các đối tượng khác

2023-08-08 14:10 UTC, st-quangnguyen2 commented on html-exercise/assets/css/style.css
> +
thêm `selector` `.product` phía trước để chỉ định chỉ đc apply với `product`

2023-08-08 14:10 UTC, st-quangnguyen2 commented on html-exercise/assets/css/style.css
> +}
đưa vào file `icon`

2023-08-08 14:13 UTC, st-quangnguyen2 commented on html-exercise/index.html
> +          <div class="product2">
class ở đây vẫn là `product`, nếu như em muốn chỉ định vị trí thứ 2 của nó thì có thể add thêm `product-2`
`product product-2`

2023-08-08 14:15 UTC, st-quangnguyen2 commented on html-exercise/index.html
> +        <li class="highlight-item highlight-item-1">
thay vì thêm class kiểu `...-{nth}`. thì em có thể không cần thêm.
dùng `selector` `nth` để css

2023-08-08 14:17 UTC, st-quangnguyen2 commented on html-exercise/assets/css/style.css
> +.highlight-item-3{
thêm `space` ở đây, phía trước `{`

2023-08-08 14:17 UTC, st-quangnguyen2 commented on html-exercise/assets/css/style.css
> +
thêm `selector` `highlight`

2023-08-08 14:19 UTC, st-quangnguyen2 commented on html-exercise/index.html
> +          <a class="nav-link yellow" href="">Men</a>
`yellow` -> `txt-yellow` nếu em muốn chỉ định màu cụ thể

2023-08-08 14:23 UTC, st-quangnguyen2 commented on html-exercise/index.html
>          <li class="product-item">
tạo cho anh một `module` `row col` tương tự boostrap để xử lý layout chỗ `ul li` này
kết quả mọng đợi như sau
```
ul.product-list.row
  li.product-item.col.col-3
```

2023-08-08 14:26 UTC, st-quangnguyen2 commented on html-exercise/assets/css/style.css
> +}
theo design thì `discount` nó chỉ có tác dụng khi nằm bên trong `product`
-> `selector` thiếu `product`

2023-08-08 14:26 UTC, st-quangnguyen2 commented on html-exercise/assets/css/style.css
> +}
xem xét đưa vào file `button`

2023-08-08 14:28 UTC, st-quangnguyen2 requested changes
@st-khanhngo check cmts

2023-08-08 18:26 UTC, st-khanhngo commented on html-exercise/index.html
> +          <div class="product2">
chỗ này type lộn mà không để ý á sorry a

2023-08-08 18:30 UTC, st-khanhngo commented on html-exercise/assets/css/style.css
> +}
<img width="182" alt="Screen Shot 2023-08-09 at 01 29 22" src="https://github.com/st-khanhngo/FE-Internship-2023_Khanh-Ngo-H_FE-Exercise/assets/141203042/d3843128-fc89-42ad-bb3e-234ebfb92b79">
ở đây cũng có discount á, còn phần discount của product em đã có selector .product rồi a

2023-08-10 02:29 UTC, st-quangnguyen2 approved these changes

2023-08-10 02:29 UTC, merged